### ISSUE TITLE
Check-in of webelexis-agenda

### ISSUE THREAD

**Issue by col-panic** [rgwch/webelexis#1]
Hy gerry,
I tried to check-in the webelexis-agend project into my Eclipse. I thowever fails with quite a weird project structure (see enclosed image). Could you give me a hint on the tools you used to get this project to correctly build?

thanks

![2015-03-11_1509](https://cloud.githubusercontent.com/assets/1679857/6597975/b28816b4-c800-11e4-8d8f-9811df9d365b.png)

**Comment by rgwch** [comment]
Did you run  "gradle eclipse" after checkout? This creates the eclipse .project file.

**Comment by col-panic** [comment]
no i didn't! I am not familiar with gradle :) looks much better now, 
thank you!!

rgwch schrieb:

**Comment by col-panic** [comment]
It did not quite work out, I got the error Cannot nest 'webelexis-agenda/src/main/java' inside 'webelexis-agenda/src'.

Luckily I found the solution on https://stackoverflow.com/questions/27692108/build-gradle-for-eclipse-project-with-multiple-source-folders - that is executing a full gradle cleanEclipseClasspath eclipse which leaves me with a running setup! You already provide a .classpath in your sources, and only executing gradle eclipse amends the already existing one!

**Comment by rgwch** [comment]
Oops, so I better remove .classpath from the repository. Thank you!

BTW: webelexis-Agenda is finished now, I continue work only on webelexis-base. This will integrate code from webelexis-agenda later.

**Comment by col-panic** [comment]
Thanks for the info! I am currently doing first steps on a headless Elexis service, and trying to figure out on how to integrate the different technologies s.t. webelexis-agend could be added as a plugin to this service. (see https://redmine.medelexis.ch/issues/3381)

**Comment by rgwch** [comment]
Thanks. I think integrating as a plugin would prove difficult. You'd have to deal with two frameworks: eclipse and vertx. 
 
One idea I thought over was running the ch.elexis.core.data.* classes from the vertx-module, which worked, but then you have a lot of legacy code from the very beginning of elexis, which has issues (e.g. too many and sometimes inefficient database accesses - I may say that, since I am the person, who is guilty for these :) )

I think it is better just to define Interfaces where the rcp app and the web app could communicate. 
I'll do it independently anyway and thus am not bound to legacy code problems (but there might arise compatibility issues while Elexis develops, though...)

**Comment by col-panic** [comment]
I don't really see the problems in combining those technologies, but 
merely selecting a set that matches future requirements. Currently I am 
creating an Equinox service providing the framework for adding headless 
plugins (e.g. eHC connector, or the webelexis agenda). I want to leave 
every plugin the required freedom but limit them to using the following 
things

* They must not open a HTTP server for themselves, the core passes them 
-> url e.g. http://doctorshost.com/webelexis-agenda where the core takes 
http://doctorshost.com and forces ssl or something and then passes to 
the resp. plugin
* The plugins must not do direct JDBC statements, they may only use the 
default Elexis Query and PO structure, with a dedicated JDBC user 
limited to a minimal set of rights (e.g. the framework would specify 
that for webelexis-agend you need read and write on the TERMINE table), 
removing the plugin removes the rights to TERMINE for this user
* For 3.1 we will refactor user and rights management .. to this end 
mandators will be able to configure who will be able to access the 
external interface via the default Elexis instance, forcing to use the 
elexis connector for headless plugins will enforce the resp. rights
* ... currently working on it! I like vert.x however, especially the 
websockets part which seems not available in Jetty!
* I don't see the problem with performance, connecting to a single 
instance leaves much room for cache management - and if this headless 
works out correctly we plan a "soft migration" to move PersistentObject 
to a server and "replace" client PO with calls to this server, where 
caching could be used more extensively!

all the best

rgwch schrieb:

**Comment by rgwch** [comment]
Sounds great, we'll see how things develop. Thanks for updating me.

**Comment by col-panic** [comment]
Just a short question: Did you stumble upon CometD when selecting vert.x, if yes is there any reason you favoured vert.x? Because I am trying to figure out the integration, and as far as I see now, CometD would provide an easy integration with Jetty, which easily integrates with Equinox, while vert.x does not! Thanks!

**Comment by rgwch** [comment]
If I understand it correctly, CometD is all about communication/ a java implementation of Comet. Vert.x is an application platform which happens to offer also a communication technique.
What I like with vert.x:
* It is really simple. I understood the concept instantly.
* It scales out with no additional effort. Launch an arbitrarily number of verticles to share load, or launch it with -cluster to build a cluster over several machines.
* It is polyglot. You can write a verticle in Java, Scala, JavaScript, Ruby or Groovy and probably more. You can even launch a Java source file as verticle: Vert.X will compile it on the fly.  And all works neatly together.
* It is "thin": Other frameworks tend to limit your freedom. Vert.X doesn't. It plays neatly and nicely with all the kids in town. It does just one thing and you are free to do all the other things in your way.

Of course, this is only my opinion after some looking around (I was especially interested in eclipse-based solutions, since Eclipse is my primary 'field of competence'. But I didn't find any I understood and liked so instantly as I did with vert.x.)

Probably other tools will to the job as well, but for me, this seems best now.

**Comment by col-panic** [comment]
Although I would really like to, after nearly 2 days of working into the technologies I don't currently see a way to integrate and use your vert.x based technology, due to the following reasons:

* For the sake of release engineering and updates to be deployed we want to stick to osgi base technologies as we know about p2 and the update processes. So for the headless structure this is a must. 
* For the sake of management, ease of configuration (firewall-friendliness!!) and security I can only allow one main HttpServer to be accepting incoming requests, which for OSGi compatibility is Jetty (here I may also set my HTTPContexts to ensure security requirements). As said, I would like to have vert.x (see See e.g. https://stackoverflow.com/questions/29004121/combine-jetty-and-vert-x .) but I don't see a way to pass an existing connection to vert.x - vert.x always wants its own server.
* I massively like the JS <-EventBus-> Service approach, hence my question to CometD. When bringing your agenda to the customer we would also have to provide ease of configuration. To this end we would implement an admin interface (probably using an Orion instance) where the customer could directly edit the resp. html files to adapt to his requirements which again is Jetty but not vert.x compatible.
* To scale, in my opionion, is not a requirement for our scenario, as its directed toward the customer having control over his data and remote access to the database. 
We also have to consider future requirements to technologies like OSGI JAX-RS for later machine-machine communication. 

So in order to get webelexis running in this scenario I think we would have to do the following:
* replace vert.x (which i see is only big trouble for the eventbus, the default getRequest to fetch the index.html is not a big problem) eventbus with something like CometD
* remove the direct SQL modifications and change to the elexis.core.data methods
* OSGIfy it
* provide a configuration interface
* ... some more stuff

Just to keep you updated! A more formal report will be available in the ticket! :)

**Comment by rgwch** [comment]
No problem. Sometimes it's better to try different approaches and see, what's best. At the end the user (myself in the first place :)) can install whatever they prefer. Database access remains open to the owner of the database I suppose.
