### ISSUE TITLE
Running webelexis against (unprotected) ES (FHIR transport)

### ISSUE THREAD

**Issue by col-panic** [rgwch/webelexis#4]
I'm trying to run webelexis agains an unprotected ES, to achieve this, I perform the following changes

1.  Start Elexis-Server with the `-Ddisable.web.security=true` flag as documented in https://github.com/elexis/elexis-server/wiki/SMART-on-FHIR#deactivating-the-security-filter
2. Reconfigure webelexis against ES in  `client/aurelia_project/environments/dev.ts` by setting `baseURL: 'http://localhost:8380/fhir/'`
3. Starting the client with `au run --watch`

Now in firefox I see that the fhir/metadata is correctly loaded. But ES cannot satisfy the requests to socket.io (e.g. `http://localhost:8380/socket.io/?EIO=3&transport=polling&t=MWiY2QG`)

* What is socket.io used for, is it possible to deactivate its functionality for the time beeing to log-in?
* Is it possible to skip login for the webelexis client?

I just want to be able to execute FHIR calls against ES using webelexis, in order to find out about the current state!

**Comment by rgwch** [comment]
This can't work currently. Webelexis/feathers uses SocketIO as transport layer because of its bidirectional nature. So the client has not to poll the server for changes on data objects,

To change this, the Interface IDataSource of the client must be reimplemented with a REST process that communicates via FHIR and polls the server regularly for changes. That's quite some days of work. I can assist with that after the frontend has all features I need for my work.

**Comment by col-panic** [comment]
ok. so it's used to inform the client about changes on data objects. That is very interesting, I thought about doing something like that too. 

So you say, that currently you don't use FHIR at all to access the data objects on the server?

**Comment by rgwch** [comment]
That's right. Iteration 2 (git checkout webelexis-2-branch) was FHIR based, but I didn't reach what I wanted, and started over with a solution I could readily test&use in my own practice. Here in Iteration 3 the transport is [FeathersJS](https://feathersjs.com/) based (Which allows for quite fast implementation of needed datatypes from their database representation).
But as I said: It's still possible to change the transport layer. But it's something that needs developer power/time.

**Comment by col-panic** [comment]
Allright - we would really like to have webelexis as a FHIR based client!

If you could provide the framework and some examples, I might be able to assist! In order to run against ES we would also need the OAuth2 authentication path being available later on.

I think we should get it as far, that anyone that uses ES should be able to opt-in for webelexis.

**Comment by col-panic** [comment]
This should be the FHIR specific style of getting updates on object changes https://www.hl7.org/fhir/subscription.html

**Comment by rgwch** [comment]
hl7.org seems to be down today

**Comment by rgwch** [comment]
Ok I'll try to provide a starter to show how to reimplement
IDataSource for the Elexis-Server with login and an example DataService.

Am 08.01.19 um 13:01 schrieb Marco Descher:

**Comment by rgwch** [comment]
@col-panic is there a concept in ES to retrieve metadata such as list of defined mandators, terminstates, termintypes, colors and so on?

**Comment by col-panic** [comment]
Hmm. I think you have to ask for each of these points in separate, as soon as the need arises. I try to clarify for your mentioned elements.

Generally ES features both a FHIR and a swagger based interface. For vue.js i have created a plugin in https://www.npmjs.com/package/@col.panic/vue-es that eases consumption of both. However, we have a FHIR first approach, for everything that is coverable with FHIR.

1. Mandators: FHIR: Query for [Practitioner](https://www.hl7.org/fhir/practitioner.html)
2. TerminStates: FHIR: Mapped to the FHIR defined states: [AppointmentStatus](https://www.hl7.org/fhir/valueset-appointmentstatus.html)
3. TerminTypes: not yet mapped - I propose [Appointment.appointmentType](https://www.hl7.org/fhir/v2/0276/index.html)
4. Colors: Not coverable via FHIR - But I started working on a SWAGGER provided configService that maps to the internal config/userconfig tables

**Comment by rgwch** [comment]
Well, the need arises when creating the UI :-). Okay, I made a minimal POC for a FHIR based transport layer and login. All the fhir related stuff is in client/src/fhir. To activate it, just change the "transport" in aurelia_project/environments/dev.ts to "fhir".
Only one datatype is implemented currently: Patient. For each datatype you need an IFhirAdapter as dedined in src/fhir/fhir-api.ts and an entry in adapter-factory.ts. For examples see src/fhir/adapters.

---et voilà: 
![bildschirmfoto vom 2019-01-10 21-59-03](https://user-images.githubusercontent.com/3314994/50996730-01380d00-1523-11e9-8634-5716fffeb18a.png)

**Comment by col-panic** [comment]
I think so - just drop your specific questions, I'll try to answer them ASAP. 

I just tried to re-enact your screenshot, but Firefox (and Chrome) leave me with a server error, and the following stack trace:

```
Warning: a promise was rejected with a non-error: [object String]
    (No stack trace)
From previous event:
    FhirService.prototype.getSmartclient@webpack-internal:///./src/fhir/fhirservice.ts:105:16
    FhirDataService.prototype.smart/</<@webpack-internal:///./src/fhir/fhir-api.ts:148:46
    step@webpack-internal:///./src/fhir/fhir-api.ts:51:18
    verb/<@webpack-internal:///./src/fhir/fhir-api.ts:32:53
    __awaiter</<@webpack-internal:///./src/fhir/fhir-api.ts:26:71
From previous event:
    __awaiter<@webpack-internal:///./src/fhir/fhir-api.ts:22:12
    FhirDataService.prototype.find@webpack-internal:///./src/fhir/fhir-api.ts:177:16
    CommonViewer.prototype.doFilter@webpack-internal:///components/commonviewer:93:9
    evaluate@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:1584:14
    callSource@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5287:18
    handleEvent@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5296:5 bluebird.js:1564

Warning: a promise was rejected with a non-error: [object String]
    (No stack trace)
From previous event:
    __awaiter<@webpack-internal:///./src/fhir/fhir-api.ts:22:12
    FhirDataService.prototype.find@webpack-internal:///./src/fhir/fhir-api.ts:177:16
    CommonViewer.prototype.doFilter@webpack-internal:///components/commonviewer:93:9
    evaluate@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:1584:14
    callSource@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5287:18
    handleEvent@webpack-internal:///./node_modules/aurelia-binding/dist/native-modules/aurelia-binding.js:5296:5 2 bluebird.js:1564

No 'state' parameter found in authorization response. index.ts:23
```

What am I doing wrong? thanks

**Comment by rgwch** [comment]
Nothing. I missed that the smartclient still wants a valid authentication. Even if the elexis-server doesn't. (smart's error message is: "No 'state' parameter found in authorization response.")
A dirty workaround is to remove the other dirty authenticate workaround temporarily: 

      // in file client/src/services/session.ts
         constructor(private ds: DataSource, private we: WebelexisEvents) {
         // Warning: Dirty workaround ahead
          /* if (env.transport === "fhir") {
               this.currentUser = new User({
                  email: "admin@webelexis.ch",
                   roles: ["admin", "guest", "user", "mpa"]
                 })
              } */
           }

And launch once. a Button "fhir login" will appear and invite you to click. The message "we are logged in" will then appear after you completed the 2FA to tell that smartclient got a valid token from the server. Then you can remove the /* */ to enable implicit login and the next start should log you in automagically as long as the token is valid.

Or just wait till tomorrow or so and then pull again. I'll fix this, but I need some time since smartclient has no real documentation as far as I found (And your example in @col.panic/vue-es has no source code attached).

**Comment by col-panic** [comment]
Great! I'll wait until your push then! I Just sent you the sources for vue-es per mail. The only documentation I know of is in http://docs.smarthealthit.org/clients/javascript/. It worked good for me.

**Comment by rgwch** [comment]
Now it should work as expected (which is not much, since "Patient" is the only datatype I implemented), This should be enough as a proof of concept. If you like, you can play around and add functionality corresponding to Elexis Server. I will concentrate rather on the UI, because I want as soon as possible a fully functional Elexis-Client for myself, and ES can't handle my needs yet.

**Comment by col-panic** [comment]
Thanks a lot! I'm just experimenting a little bit with it (hooray smart login works!!!), and found 2 points I'm puzzling with:

* Searching for patients seem to take the detail-info only from the values available within the search, now a succinct detail query for the patients id (as most of the data is missing) - is that right?
* Trying to add a new patient, it seems that Elexis->Fhir mapping is not working, as in `BaseAdapter#toFhirObject` the value` eo.type is undefined` which leads to the fact, that ES does not know what to do with it! How may I fix this?

**Comment by rgwch** [comment]
* For the list view, only data of a "search" operation is used. If that is not sufficient, a second call to the resource id is necessary to retrieve all data - to implement later.

* tried to fix but can't test since I get: `Access to XMLHttpRequest at 'http://localhost:8380/fhir/Patient' from origin 'http://localhost:9000' has been blocked by CORS policy: Request header field prefer is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by col-panic** [comment]
>     * For the list view, only data of a "search" operation is used. If that is not sufficient, a second call to the resource id is necessary to retrieve all data - to implement later.

Thanks for the info!

>     * tried to fix but can't test since I get: `Access to XMLHttpRequest at 'http://localhost:8380/fhir/Patient' from origin 'http://localhost:9000' has been blocked by CORS policy: Request header field prefer is not allowed by Access-Control-Allow-Headers in preflight response.`

Updating the patient, resp. adding a new one is not implemented yet! I wanted to use webelexis as a first case to implement the required methods! Could you just provide your preliminary patch (maybe in a separate branch) or post it here - I could give you more feedback than!

**Comment by col-panic** [comment]
Allright - I'm getting the first impressions ;) What i did not find out, is how to support the modify operation! Modifying the details of a patient, and the pressing the save symbol, does not cause a resp. update call to ES! Could you give me a hint there? thanks

**Comment by rgwch** [comment]
It hangs here:

~~~
// fhir-api.ts
 // update an object with id
  public update(index, obj): ElexisType {
    return;
  }

  // Update only given attributes of an existing object
  public patch(index, obj): ElexisType {
    return null;
  }

  // delete an object (or several objects)
  public remove(index, params?): ElexisType {
    return null;
  }
~~~

Since I didn't find the call API for the fhir-client for update, patch and delete operations, I just left them empty. We could either  call the REST Api of the FHIR server or try to find out fhir client's API, e.g. by analyzing the source code or finding documentation somewhere... But both is quite tedious,.

Thanks for the fixes!

**Comment by col-panic** [comment]
I found a nice link :) https://healthservices.atlassian.net/wiki/spaces/HSPC/pages/64585804/How+to+Update+a+Patient+Record - update seems to work!

**Comment by col-panic** [comment]
Is it possible, that articles are not fetched via a service? I tried to understand how to add an article-service to connect it with ES?!

**Comment by rgwch** [comment]
Since Elexis has several Article systems, I handle them with a "meta-article" service which tries to find a requested object wherever it might be and returns it as an "ArticleType" with a "scoped id" such as "ch.artikelstamm.elexis.common.ArtikelstammItem::sddff32344" or "ch.elexis.data.Artikel::223445eer".
 
Creating or updating of articles is not covered at all (Webelexis is only an addition, not a replacement for Elexis). So you'd have to implement 'meta-article', 'prescription' and 'rezept' for the fhir transport. Client side code is in models/prescription-model.ts.
